test:
	./_ready_for_testing.sh

	# A. Configuration and Settings
	./A001_rcNotFound_test.sh
	./A002_activeTable_test.sh

	# B. Simple Flags
	./B001_help_param_test.sh
	./B002_invalid_params_test.sh
	./B003_show_types_param_test.sh
	./B004_version_param_test.sh

	# C. Args
#	./C001_body_and_end_args_test.sh
#	./C002_body_arg_test.sh
#	./C003_end_arg_test.sh
#	./C004_title_and_body_args_test.sh
#	./C005_title_and_end_args_test.sh
#	./C006_title_arg_test.sh
#	./C007_title_body_and_end_test.sh
#
#	# D. Args and Prompting
#
#	# E. Flags and Args
#	./E001_message_flag_and_arg_test.sh
#	./E002_message_flag_prevents_message_prompt_test.sh
#
#	# F. Flags and Prompts
#	./F001_breaking_and_prompt_test.sh
#
#	# M. Miscellaneous

	# U. Utilities and Helpers
	./U001_set_commit_variables_test.sh